# Config file for USCS classification
# Prompt file and version
prompts_file: bedrock/prompts/bedrock_uscs_prompts.yml
prompt_version: v1

# Pattern file and parameter version
pattern_file: bedrock/examples/bedrock_uscs_examples.yml
pattern_version: v1

# Tool file
tool_file: bedrock/tool/tool_classify_single.yml

# temperature - answer creativity for the LLM model
temperature: 0.0

# Maximum response tokens
max_tokens: 4096

# Parameter indicating if Reasoning (Chain of Thought) mode should be used. Warning this significantly increases latency
reasoning_mode: False
