# model_path: "google-bert/bert-base-uncased"
model_path: "google-bert/bert-base-multilingual-uncased"

# Data parameters
classification_system: "uscs"
json_file_name: "geoquat_ground_truth.json"
train_subset: "geoquat/train"
eval_subset: "geoquat/validation"

# Training hyperparameters
batch_size: 32
num_epochs: 32
learning_rate: 1e-4
weight_decay: 0.001
warmup_ratio: 0.1
#lr_scheduler_type: "cosine"
lr_scheduler_type: "cosine_with_restarts"
max_grad_norm: 5.0
# Custom Training hyperparameters
unfreeze_layers:
  - "classifier"
  - "pooler"
  - "layer_11"
use_class_balancing: "false"

# Inference parameters
inference_batch_size: 32