
uscs_patterns:
  baseline:
    de:
      CH: ["fetter Ton"]
      CL: ["siltiger Ton", "Lehm, Feinsand"]
      CL-ML: ["toniger Silt", "tonig-sandiger Silt"]
      CM: ["magerer Ton"]
      G: ["Kies", "Kiessand"]
      G-GC: ["schwach toniger Kies", "leicht toniger Kies"]
      G-GM: ["schwach siltiger Kies", "leicht siltiger Kies"]
      GC: ["toniger Kies", "Kies, Lehm"]
      GC-GM: ["siltiger bis toniger Kies"]
      GM: ["siltiger Kies"]
      GP: ["schlecht abgestufter Kies", "grober Kies", "mittelgrober Kies", "sandiger Feinkies", "Grobkies", "Feinkies"]
      GP-GC: ["schlecht abgestufter Kies mit Ton"]
      GP-GM: ["schlecht abgestufter Kies mit Silt", "siltiger Grobkies", "siltiger Mittelkies", "siltiger Feinkeis"]
      GW: ["gut abgestufter Kies"]
      GW-GC: ["gut abgestufter Kies mit Ton"]
      GW-GM: ["gut abgestufter Kies mit Silt"]
      MH: ["elastischer Silt"]
      ML: ["Silt", "Siltsand", "Silt, Kies", "sandiger Lehm"]
      OH: ["organischer Silt", "Humus", "humoser Silt"]
      OL: ["organischer Ton", "Humus und Sand"]
      S: ["Sand", "Sand, Kies"]
      S-SC: ["schwach toniger Sand", "leicht toniger Sand"]
      S-SM: ["schwach siltiger Sand", "leicht siltiger Sand", "leicht siltiger Feinsand", "leicht siltiger Mittelsand"]
      SC: ["toniger Sand", "lehmiger Sand"]
      SC-SM: ["siltiger, toniger Sand", "Sand, verlehmt, siltig"]
      SM: ["siltiger Sand"]
      SP: ["schlecht abgestufter Sand", "grobkörniger Sand", "mittelkörniger Sand", "feinkiesiger Mittelsand"]
      SP-SC: ["schlecht abgestufter Sand mit Ton", "Feinsand, Lehm", "toniger Feinsand"]
      SP-SM: ["schlecht abgestufter Sand mit Silt", "siltiger Feinsand", "siltiger Mittelsand", "siltiger Grobsand", "siltiger Feinkies"]
      SW: ["gut abgestufter Sand", "Sand, Kies, Silt"]
      SW-SC: ["gut abgestufter Sand mit Ton"]
      SW-SM: ["gut abgestufter Sand mit Silt", "Grobmittelsand, siltig", "Feinmittelsand, siltig"]
      Bl: ["Block"]
      FELS: ["Fels", "Sandstein", "Tonstein", "Mergel", "Molasse", "Kalk", "Sandsteinbrocken", "Sandsteinmolasse", "Gips"]
      kA: ["keine Angabe", "unbekannt", "nicht beschrieben"]
      kunst: ["Auffüllung", "Aufschüttung", "Beton"]
      Pt: ["Torf"]
      St: ["Stein"]
      St-Bl: ["Steine und Blöcke"]
    fr:
      CH: ["argile grasse"]
      CL: ["argile limoneuse", "argile", "argileux"]
      CL-ML: ["limon argileux"]
      CM: ["argile maigre"]
      G: ["gravier"]
      G-GC: ["gravier peu argileux"]
      G-GM: ["gravier peu limoneux"]
      GC: ["gravier argileux"]
      GC-GM: ["gravier limono-argileux"]
      GP: ["gravier mal gradué", "gravier moyen", "gravier grossier"]
      GP-GC: ["gravier mal gradué avec argile"]
      GP-GM: ["gravier mal gradué avec limon", "gravier moyen, limoneux", "gravier grossier, limoneux"]
      GM: ["gravier limoneux"]
      GW: ["gravier bien gradué"]
      GW-GM: ["gravier bien gradué avec limon", "gravier, galets, limoneux", "gravier, éléments roulés, limoneux"]
      GW-GC: ["gravier bien gradué avec argile"]
      MH: ["limon élastique"]
      ML: ["limon"]
      OH: ["limon organique", "végétal"]
      OL: ["argile organique"]
      S: ["sable", "sableux"]
      S-SC: ["sable peu argileux"]
      S-SM: ["sable peu limoneux"]
      SC: ["sable argileux"]
      SC-SM: ["sable limono-argileux"]
      SM: ["sable limoneux"]
      SP: ["sable mal gradué", "sable moyen", "sable grossier"]
      SP-SC: ["sable mal gradué avec argile"]
      SP-SM: ["sable mal gradué avec limon", "sable moyen, limoneux"]
      SW: ["sable bien gradué"]
      SW-SC: ["sable bien gradué avec argile"]
      SW-SM: ["sable bien gradué avec limon"]
      Bl: ["bloc"]
      FELS: ["rocher", "marne", "marno", "molasse", "gypse", "schistes"]
      kA: ["sans indication"]
      kunst: ["remplissage artificiel", "bitume", "bitumineux"]
      Pt: ["tourbe"]
      St: ["pierre"]
      St-Bl: ["pierre et bloc"]

    en:
      kunst: ["artificial landfill"]
      Bl: ["boulder"]
      GP: ["poorly graded gravel"]
      CH: ["fat clay"]
      CM: ["lean clay"]
      CL: ["silty clay"]
      CL-ML: ["clayey silt"]
      G: ["gravel"]
      S: ["sand"]
      GW-GC: ["well-graded gravel with clay"]
      Pt: ["peat"]
      ML: ["silt"]
      GM: ["silty gravel"]
      kA: ["not specified"]
      FELS: ["bed rock"]
      SC: ["clayey sand"]
      S-SM: ["slightly silty sand"]
      SM: ["silty sand"]
      SP: ["poorly graded sand"]
      SP-SC: ["poorly graded sand with clay"]
      SP-SM: ["poorly graded sand with silt"]
      SW: ["well-graded sand"]
      SW-SC: ["well-graded sand with clay"]
      SW-SM: ["well-graded sand with silt"]
      G-GC: ["slightly clayey gravel"]
      G-GM: ["slightly silty gravel"]
      St: ["cobbles"]
      St-Bl: ["cobbles and boulders"]
      OH: ["organic silt"]
      OL: ["organic clay"]
      S-SC: ["slightly clayey sand"]
      SC-SM: ["silty, clayey sand"]
      GC: ["clayey gravel"]
      GC-GM: ["silty, clayey gravel"]
      GP-GC: ["poorly graded gravel with clay"]
      GP-GM: ["poorly graded gravel with silt"]
      GW: ["well-graded gravel"]
      GW-GM: ["well-graded gravel with silt"]
      MH: ["elastic silt"]
    it:
      kunst: ["riempimento artificiale"]
      Bl: ["blocco"]
      GP: ["ghiaia mal classata"]
      CH: ["argilla grassa"]
      CM: ["argilla magra"]
      CL: ["argilla limosa"]
      CL-ML: ["limo argilloso"]
      G: ["ghiaia"]
      S: ["sabbia"]
      GW-GC: ["ghiaia ben con argilla"]
      Pt: ["torba"]
      ML: ["limo"]
      GM: ["ghiaia limosa"]
      kA: ["senza indicazioni"]
      FELS: ["roccia"]
      SC: ["sabbia argillosa"]
      S-SM: ["sabbia leggermente limosa"]
      SM: ["sabbia limosa"]
      SP: ["sabbia mal classata"]
      SP-SC: ["sabbia mal classata con argilla"]
      SP-SM: ["sabbia mal classata con limo"]
      SW: ["sabbia ben classata"]
      SW-SC: ["sabbia ben classata con argilla"]
      SW-SM: ["sabbia ben classata con limo"]
      G-GC: ["ghiaia leggermente argillosa"]
      G-GM: ["ghiaia leggermente limosa"]
      St: ["pietra"]
      St-Bl: ["pietre e blocchi"]
      OH: ["limo organico"]
      OL: ["argilla organica"]
      S-SC: ["sabbia leggermente argillosa"]
      SC-SM: ["sabbia limo argillosa"]
      GC: ["ghiaia argillosa"]
      GC-GM: ["ghiaia limoso argillosa"]
      GP-GC: ["ghiaia mal classata con argilla"]
      GP-GM: ["ghiaia mal classata con limo"]
      GW: ["ghiaia ben classata"]
      GW-GM: ["ghiaia ben con limo"]
      MH: ["limo elastico"]

