# Default parameters used for the borehole name detection pipeline, used as part of the swissgeol_doc_processing package.
# These paramaters should be changed only if we want to impact the functionality of the package globally.

# Overlap threshold for closest next line detection.
min_vertical_overlap: 0.5
# Max allowed distance between keyword and next line
max_horizontal_distance: 50

# For matching_keywords_suffix, respect the following rules
# * Keyword should match the end of word (e.g.: bohrung -> kernbohrung, rammkernbohrung)
# * Keyword is case insensitive
# * Keywords are ignored for borehole name matching : "12" == "bohrung 12"
matching_keywords:
  [
    "baggerschacht",
    "baggerschlitz",
    "bohrstelle",
    "forage",
    "kernbohrung",
    "probenahmestelle",
    "rammkernbohrung",
    "rammsondierung",
    "rotationsbohrung",
    "rotationskernbohrung",
    "schachtprofil",
    "sondierbohrung",
    "sondierschacht",
    "sondage à la pelle",
    "sondage carotté",
    "sondage",
    "tranchée",
    "bohrung",
    "schacht",
    "sondierung",
    "coupe de fouille",
    "coupe du forage",
    "fouille"
  ]

# Keyword to ignore in borehole name detection and evaluation
excluded_keywords: ["n", "nr.", "nr", "n r", "n°", "nº", "no", "nummer"]
