classification_system: "en_main"
experiment_name: "en_main"
model_path: "google-bert/bert-base-multilingual-uncased"
use_class_balancing: false
inference_batch_size: 32

# Training and testing sets
training_sets:
  en_main:
    classification_system: en_main
    ground_truths:
      - deepwells_ground_truth.json
      - geoquat_ground_truth.json
      - nagra_ground_truth.json
      - thurgau_ground_truth.json
      - zurich_ground_truth.json

test_sets:
  global_en_main:
    classification_system: en_main
    ground_truths:
      - deepwells_ground_truth.json
      - geoquat_ground_truth.json
      - nagra_ground_truth.json
      - thurgau_ground_truth.json
      - zurich_ground_truth.json
  deepwells_en_main:
    classification_system: en_main
    ground_truths:
      - deepwells_ground_truth.json
  geoquat_en_main:
    classification_system: en_main
    ground_truths:
      - geoquat_ground_truth.json
  nagra_en_main:
    classification_system: en_main
    ground_truths:
      - nagra_ground_truth.json
  thurgau_en_main:
    classification_system: en_main
    ground_truths:
      - thurgau_ground_truth.json
  zurich_en_main:
    classification_system: en_main
    ground_truths:
      - zurich_ground_truth.json

# Custom Training hyperparameters
hyperparameters:
  batch_size: 32
  learning_rate: 1e-4
  lr_scheduler_type: "cosine_with_restarts"
  max_grad_norm: 5.0
  num_epochs: 32
  warmup_ratio: 0.1
  weight_decay: 0.001

# Layer to train
unfreeze_layers:
  - "classifier"
  - "pooler"
  - "layer_11"
