classification_system: "alteration_degree"
experiment_name: "alteration_degree_all_to_all"
model_path: "google-bert/bert-base-multilingual-uncased"
use_class_balancing: false
inference_batch_size: 32

# Training and testing sets
training_sets:
  consolidated:
    classification_system: alteration_degree_consolidated
    ground_truths:
      - geoquat_ground_truth.json
      - nagra_ground_truth.json
  unconsolidated:
    classification_system: alteration_degree_unconsolidated
    ground_truths:
      - geoquat_ground_truth.json
      - nagra_ground_truth.json

test_sets:
  # Consolidated test (+ global)
  global_consolidated:
    classification_system: alteration_degree_consolidated
    ground_truths:
      - geoquat_ground_truth.json
      - nagra_ground_truth.json
  geoquat_consolidated:
    classification_system: alteration_degree_consolidated
    ground_truths:
      - geoquat_ground_truth.json
  nagra_consolidated:
    classification_system: alteration_degree_consolidated
    ground_truths:
      - nagra_ground_truth.json
  # Unconsolidated test (+ global)
  global_unconsolidated:
    classification_system: alteration_degree_unconsolidated
    ground_truths:
      - geoquat_ground_truth.json
      - nagra_ground_truth.json
  geoquat_unconsolidated:
    classification_system: alteration_degree_unconsolidated
    ground_truths:
      - geoquat_ground_truth.json
  nagra_unconsolidated:
    classification_system: alteration_degree_unconsolidated
    ground_truths:
      - nagra_ground_truth.json

# Custom Training hyperparameters
hyperparameters:
  batch_size: 32
  learning_rate: 1e-4
  lr_scheduler_type: "cosine_with_restarts"
  max_grad_norm: 5.0
  num_epochs: 32
  warmup_ratio: 0.1
  weight_decay: 0.001

# Layer to train
unfreeze_layers:
  - "classifier"
  - "pooler"
  - "layer_11"
