default_language: de
supported_language: [de,fr,en,it]
uscs_patterns:
  de:
    CH: should be used for 'fetter Ton'
    CL: should be used for 'siltiger Ton' or'Lehm' or 'Feinsand'
    CL-ML: should be used for toniger Silt or 'tonig-sandiger Silt
    CM: should be used for 'magerer Ton'
    G: should be used for 'Kies', 'Kiessand'
    G-GC: should be used for 'schwach toniger Kies', 'leicht toniger Kies'
    G-GM: should be used for 'schwach siltiger Kies', 'leicht siltiger Kies'
    GC: should be used for 'toniger Kies', 'Kies, Lehm'
    GC-GM: should be used for 'siltiger bis toniger Kies'
    GM: should be used for 'siltiger Kies'
    GP: should be used for 'schlecht abgestufter Kies', 'grober Kies', 'mittelgrober Kies', 'sandiger Feinkies', 'Grobkies', 'Feinkies'
    GP-GC: should be used for 'schlecht abgestufter Kies mit Ton'
    GP-GM: should be used for 'schlecht abgestufter Kies mit Silt', 'siltiger Grobkies', 'siltiger Mittelkies', 'siltiger Feinkeis'
    GW: should be used for 'gut abgestufter Kies'
    GW-GC: should be used for 'gut abgestufter Kies mit Ton'
    GW-GM: should be used for 'gut abgestufter Kies mit Silt'
    MH: should be used for 'elastischer Silt'
    ML: should be used for 'Silt', 'Siltsand', 'Silt, Kies', 'sandiger Lehm'
    OH: should be used for 'organischer Silt', 'Humus', 'humoser Silt'
    OL: should be used for 'organischer Ton', 'Humus und Sand'
    S: should be used for 'Sand', 'Sand, Kies'
    S-SC: should be used for 'schwach toniger Sand', 'leicht toniger Sand'
    S-SM: should be used for 'schwach siltiger Sand', 'leicht siltiger Sand', 'leicht siltiger Feinsand', 'leicht siltiger Mittelsand'
    SC: should be used for 'toniger Sand', 'lehmiger Sand'
    SC-SM: should be used for 'siltiger, toniger Sand', 'Sand, verlehmt, siltig'
    SM: should be used for 'siltiger Sand'
    SP: should be used for 'schlecht abgestufter Sand', 'grobkörniger Sand', 'mittelkörniger Sand', 'feinkiesiger Mittelsand'
    SP-SC: should be used for 'schlecht abgestufter Sand mit Ton', 'Feinsand, Lehm', 'toniger Feinsand'
    SP-SM: should be used for 'schlecht abgestufter Sand mit Silt', 'siltiger Feinsand', 'siltiger Mittelsand', 'siltiger Grobsand', 'siltiger Feinkies'
    SW: should be used for 'gut abgestufter Sand', 'Sand, Kies, Silt'
    SW-SC: should be used for 'gut abgestufter Sand mit Ton'
    SW-SM: should be used for 'gut abgestufter Sand mit Silt', 'Grobmittelsand, siltig', 'Feinmittelsand, siltig'
    Bl: should be used for 'Block'
    FELS: should be used for 'Fels', 'Sandstein', 'Tonstein', 'Mergel', 'Molasse', 'Kalk', 'Sandsteinbrocken', 'Sandsteinmolasse', 'Gips'
    kA: should be used for 'keine Angabe', 'unbekannt', 'nicht beschrieben'
    kunst: should be used for 'Auffüllung', 'Aufschüttung', 'Beton'
    Pt: should be used for 'Torf'
    St: should be used for Stein
    St-Bl: should be used for 'Steine und Blöcke'
  fr:
    CH: should be used for 'argile grasse'
    CL: should be used for 'argile limoneuse', 'argile', 'argileux'
    CL-ML: should be used for 'limon argileux'
    CM: should be used for 'argile maigre'
    G: should be used for 'gravier'
    G-GC: should be used for 'gravier peu argileux'
    G-GM: should be used for 'gravier peu limoneux'
    GC: should be used for 'gravier argileux'
    GC-GM: should be used for 'gravier limono-argileux'
    GP: should be used for 'gravier mal gradué', 'gravier moyen', 'gravier grossier'
    GP-GC: should be used for 'gravier mal gradué avec argile'
    GP-GM: should be used for 'gravier mal gradué avec limon', 'gravier moyen, limoneux', 'gravier grossier, limoneux'
    GM: should be used for 'gravier limoneux'
    GW: should be used for 'gravier bien gradué'
    GW-GM: should be used for 'gravier bien gradué avec limon', 'gravier, galets, limoneux', 'gravier, éléments roulés, limoneux'
    GW-GC: should be used for 'gravier bien gradué avec argile'
    MH: should be used for 'limon élastique'
    ML: should be used for 'limon'
    OH: should be used for 'limon organique', 'végétal'
    OL: should be used for 'argile organique'
    S: should be used for 'sable', 'sableux'
    S-SC: should be used for 'sable peu argileux'
    S-SM: should be used for 'sable peu limoneux'
    SC: should be used for 'sable argileux'
    SC-SM: should be used for 'sable limono-argileux'
    SM: should be used for 'sable limoneux'
    SP: should be used for 'sable mal gradué', 'sable moyen', 'sable grossier'
    SP-SC: should be used for 'sable mal gradué avec argile'
    SP-SM: should be used for 'sable mal gradué avec limon', 'sable moyen, limoneux'
    SW: should be used for 'sable bien gradué'
    SW-SC: should be used for 'sable bien gradué avec argile'
    SW-SM: should be used for 'sable bien gradué avec limon'
    Bl: should be used for 'bloc'
    FELS: should be used for 'rocher', 'marne', 'marno', 'molasse', 'gypse', 'schistes'
    kA: should be used for 'sans indication'
    kunst: should be used for 'remplissage artificiel', 'bitume', 'bitumineux'
    Pt: should be used for 'tourbe'
    St: should be used for 'pierre'
    St-Bl: should be used for 'pierre et bloc'

  en:
    kunst: should be used for 'artificial landfill'
    Bl: should be used for 'boulder'
    GP: should be used for 'poorly graded gravel'
    CH: should be used for 'fat clay'
    CM: should be used for 'lean clay'
    CL: should be used for 'silty clay'
    CL-ML: should be used for 'clayey silt'
    G: should be used for 'gravel'
    S: should be used for 'sand'
    GW-GC: should be used for 'well-graded gravel with clay'
    Pt: should be used for 'peat'
    ML: should be used for 'silt'
    GM: should be used for 'silty gravel'
    kA: should be used for 'not specified'
    FELS: should be used for 'bed rock'
    SC: should be used for 'clayey sand'
    S-SM: should be used for 'slightly silty sand'
    SM: should be used for 'silty sand'
    SP: should be used for 'poorly graded sand'
    SP-SC: should be used for 'poorly graded sand with clay'
    SP-SM: should be used for 'poorly graded sand with silt'
    SW: should be used for 'well-graded sand'
    SW-SC: should be used for 'well-graded sand with clay'
    SW-SM: should be used for 'well-graded sand with silt'
    G-GC: should be used for 'slightly clayey gravel'
    G-GM: should be used for 'slightly silty gravel'
    St: should be used for 'cobbles'
    St-Bl: should be used for 'cobbles and boulders'
    OH: should be used for 'organic silt'
    OL: should be used for 'organic clay'
    S-SC: should be used for 'slightly clayey sand'
    SC-SM: should be used for 'silty, clayey sand'
    GC: should be used for 'clayey gravel'
    GC-GM: should be used for 'silty, clayey gravel'
    GP-GC: should be used for 'poorly graded gravel with clay'
    GP-GM: should be used for 'poorly graded gravel with silt'
    GW: should be used for 'well-graded gravel'
    GW-GM: should be used for 'well-graded gravel with silt'
    MH: should be used for 'elastic silt'
  it:
    kunst: should be used for 'riempimento artificiale'
    Bl: should be used for 'blocco'
    GP: should be used for 'ghiaia mal classata'
    CH: should be used for 'argilla grassa'
    CM: should be used for 'argilla magra'
    CL: should be used for 'argilla limosa'
    CL-ML: should be used for 'limo argilloso'
    G: should be used for 'ghiaia'
    S: should be used for 'sabbia'
    GW-GC: should be used for 'ghiaia ben con argilla'
    Pt: should be used for 'torba'
    ML: should be used for 'limo'
    GM: should be used for 'ghiaia limosa'
    kA: should be used for 'senza indicazioni'
    FELS: should be used for 'roccia'
    SC: should be used for 'sabbia argillosa'
    S-SM: should be used for 'sabbia leggermente limosa'
    SM: should be used for 'sabbia limosa'
    SP: should be used for 'sabbia mal classata'
    SP-SC: should be used for 'sabbia mal classata con argilla'
    SP-SM: should be used for 'sabbia mal classata con limo'
    SW: should be used for 'sabbia ben classata'
    SW-SC: should be used for 'sabbia ben classata con argilla'
    SW-SM: should be used for 'sabbia ben classata con limo'
    G-GC: should be used for 'ghiaia leggermente argillosa'
    G-GM: should be used for 'ghiaia leggermente limosa'
    St: should be used for 'pietra'
    St-Bl: should be used for 'pietre e blocchi'
    OH: should be used for 'limo organico'
    OL: should be used for 'argilla organica'
    S-SC: should be used for 'sabbia leggermente argillosa'
    SC-SM: should be used for 'sabbia limo argillosa'
    GC: should be used for 'ghiaia argillosa'
    GC-GM: should be used for 'ghiaia limoso argillosa'
    GP-GC: should be used for 'ghiaia mal classata con argilla'
    GP-GM: should be used for 'ghiaia mal classata con limo'
    GW: should be used for 'ghiaia ben classata'
    GW-GM: should be used for 'ghiaia ben con limo'
    MH: should be used for 'limo elastico'