default_language: "de"
supported_language: ["de","fr","en","it"]
uscs_patterns:
  de:
    CH: "should contain 'fetter Ton', 'plastischer Ton', 'hochplastischer Ton'"
    CL: "should contain 'siltiger Ton', 'Lehm', 'schwach plastischer Ton'"
    CL-ML: "should contain 'toniger Silt', 'tonig-sandiger Silt', 'Mischboden Ton/Silt'"
    CM: "should contain 'magerer Ton', 'schwach plastischer Ton'"
    G: "should contain 'Kies', 'Kiessand', 'Rollkies', 'Geröll'"
    G-GC: "should contain 'schwach toniger Kies', 'leicht toniger Kies'"
    G-GM: "should contain 'schwach siltiger Kies', 'leicht siltiger Kies'"
    GC: "should contain 'toniger Kies', 'kiesiger Lehm'"
    GC-GM: "should contain 'siltiger bis toniger Kies', 'gemischter Kies mit Silt und Ton'"
    GM: "should contain 'siltiger Kies', 'kiesiger Silt'"
    GP: "should contain 'schlecht abgestufter Kies', 'grobkörniger Kies', 'mittelkörniger Kies', 'Feinkies'"
    GP-GC: "should contain 'schlecht abgestufter Kies mit Ton'"
    GP-GM: "should contain 'schlecht abgestufter Kies mit Silt', 'siltiger Grobkies', 'siltiger Mittelkies', 'siltiger Feinkies'"
    GW: "should contain 'gut abgestufter Kies', 'Kies, gut sortiert'"
    GW-GC: "should contain 'gut abgestufter Kies mit Ton'"
    GW-GM: "should contain 'gut abgestufter Kies mit Silt'"
    MH: "should contain 'elastischer Silt', 'hochplastischer Silt'"
    ML: "should contain 'Silt', 'Siltsand', 'sandiger Lehm', 'geringplastischer Silt'"
    OH: "should contain 'organischer Silt', 'Humus', 'humoser Silt', 'organischer Boden'"
    OL: "should contain 'organischer Ton', 'Humus und Sand', 'toniger Humus'"
    S: "should contain 'Sand', 'Kiessand', 'Feinsand', 'Mittelsand', 'Grobsand'"
    S-SC: "should contain 'schwach toniger Sand', 'leicht toniger Sand'"
    S-SM: "should contain 'schwach siltiger Sand', 'leicht siltiger Sand'"
    SC: "should contain 'toniger Sand', 'lehmiger Sand'"
    SC-SM: "should contain 'siltig-toniger Sand', 'Sand, verlehmt und siltig'"
    SM: "should contain 'siltiger Sand', 'sandiger Silt'"
    SP: "should contain 'schlecht abgestufter Sand', 'einheitlichkörniger Sand'"
    SP-SC: "should contain 'schlecht abgestufter Sand mit Ton', 'toniger Feinsand'"
    SP-SM: "should contain 'schlecht abgestufter Sand mit Silt', 'siltiger Sand'"
    SW: "should contain 'gut abgestufter Sand', 'Sand, gut sortiert'"
    SW-SC: "should contain 'gut abgestufter Sand mit Ton'"
    SW-SM: "should contain 'gut abgestufter Sand mit Silt'"
    Bl: "should contain 'Block'"
    FELS: "should contain 'Fels', 'Sandstein', 'Tonstein', 'Kalk', 'Gips', 'Molasse', 'Mergel'"
    kA: "should contain 'keine Angabe', 'unbekannt', 'nicht beschrieben'"
    kunst: "should contain 'Auffüllung', 'Aufschüttung', 'Beton', 'künstlich'"
    Pt: "should contain 'Torf', 'torfig'"
    St: "should contain 'Stein', 'Steine'"
    St-Bl: "should contain 'Steine und Blöcke', 'Gemisch aus Stein und Block'"
  fr:
    CH: "should contain 'argile grasse', 'argile très plastique'"
    CL: "should contain 'argile limoneuse', 'argile peu plastique'"
    CL-ML: "should contain 'limon argileux', 'sol mixte argile-limon'"
    CM: "should contain 'argile maigre', 'argile faiblement plastique'"
    G: "should contain 'gravier', 'cailloutis'"
    G-GC: "should contain 'gravier peu argileux'"
    G-GM: "should contain 'gravier peu limoneux'"
    GC: "should contain 'gravier argileux', 'cailloutis argileux'"
    GC-GM: "should contain 'gravier limono-argileux'"
    GM: "should contain 'gravier limoneux'"
    GP: "should contain 'gravier mal gradué', 'gravier uniforme'"
    GP-GC: "should contain 'gravier mal gradué avec argile'"
    GP-GM: "should contain 'gravier mal gradué avec limon'"
    GW: "should contain 'gravier bien gradué'"
    GW-GC: "should contain 'gravier bien gradué avec argile'"
    GW-GM: "should contain 'gravier bien gradué avec limon'"
    MH: "should contain 'limon élastique', 'limon très plastique'"
    ML: "should contain 'limon', 'limon peu plastique'"
    OH: "should contain 'limon organique', 'sol organique'"
    OL: "should contain 'argile organique'"
    S: "should contain 'sable'"
    SC: "should contain 'sable argileux'"
    SM: "should contain 'sable limoneux'"
    SP: "should contain 'sable mal gradué'"
    SW: "should contain 'sable bien gradué'"
  en:
    CH: "should contain 'fat clay', 'high plasticity clay'"
    CL: "should contain 'silty clay', 'low plasticity clay'"
    CL-ML: "should contain 'clayey silt', 'mixed silt and clay'"
    CM: "should contain 'lean clay', 'low plasticity clay'"
    G: "should contain 'gravel', 'coarse gravel', 'fine gravel'"
    G-GC: "should contain 'slightly clayey gravel'"
    G-GM: "should contain 'slightly silty gravel'"
    GC: "should contain 'clayey gravel'"
    GC-GM: "should contain 'silty, clayey gravel'"
    GM: "should contain 'silty gravel'"
    GP: "should contain 'poorly graded gravel', 'uniform gravel'"
    GP-GC: "should contain 'poorly graded gravel with clay'"
    GP-GM: "should contain 'poorly graded gravel with silt'"
    GW: "should contain 'well-graded gravel'"
    GW-GC: "should contain 'well-graded gravel with clay'"
    GW-GM: "should contain 'well-graded gravel with silt'"
    MH: "should contain 'elastic silt', 'high plasticity silt'"
    ML: "should contain 'silt', 'low plasticity silt'"
    OH: "should contain 'organic silt', 'humus-rich silt'"
    OL: "should contain 'organic clay', 'peaty clay'"
    S: "should contain 'sand', 'fine to coarse sand'"
    S-SC: "should contain 'slightly clayey sand'"
    S-SM: "should contain 'slightly silty sand'"
    SC: "should contain 'clayey sand'"
    SC-SM: "should contain 'silty, clayey sand'"
    SM: "should contain 'silty sand'"
    SP: "should contain 'poorly graded sand', 'uniform sand'"
    SP-SC: "should contain 'poorly graded sand with clay'"
    SP-SM: "should contain 'poorly graded sand with silt'"
    SW: "should contain 'well-graded sand'"
    SW-SC: "should contain 'well-graded sand with clay'"
    SW-SM: "should contain 'well-graded sand with silt'"
    Bl: "should contain 'boulder'"
    FELS: "should contain 'bedrock', 'sandstone', 'shale', 'gypsum', 'marl', 'limestone'"
    kA: "should contain 'not specified', 'unknown'"
    kunst: "should contain 'artificial fill', 'landfill', 'man-made fill'"
    Pt: "should contain 'peat'"
    St: "should contain 'cobble', 'cobbles'"
    St-Bl: "should contain 'cobbles and boulders'"
  fr:
    CH: "should contain 'argile grasse', 'argile très plastique'"
    CL: "should contain 'argile limoneuse', 'argile', 'argile peu plastique'"
    CL-ML: "should contain 'limon argileux', 'sol mixte argile-limon'"
    CM: "should contain 'argile maigre', 'argile faiblement plastique'"
    G: "should contain 'gravier', 'cailloutis'"
    G-GC: "should contain 'gravier peu argileux'"
    G-GM: "should contain 'gravier peu limoneux'"
    GC: "should contain 'gravier argileux', 'cailloutis argileux'"
    GC-GM: "should contain 'gravier limono-argileux'"
    GM: "should contain 'gravier limoneux'"
    GP: "should contain 'gravier mal gradué', 'gravier uniforme', 'gravier moyen', 'gravier grossier'"
    GP-GC: "should contain 'gravier mal gradué avec argile'"
    GP-GM: "should contain 'gravier mal gradué avec limon', 'gravier moyen, limoneux', 'gravier grossier, limoneux'"
    GW: "should contain 'gravier bien gradué'"
    GW-GC: "should contain 'gravier bien gradué avec argile'"
    GW-GM: "should contain 'gravier bien gradué avec limon', 'gravier, galets, limoneux', 'gravier, éléments roulés, limoneux'"
    MH: "should contain 'limon élastique', 'limon très plastique'"
    ML: "should contain 'limon', 'limon peu plastique'"
    OH: "should contain 'limon organique', 'sol organique', 'végétal'"
    OL: "should contain 'argile organique'"
    S: "should contain 'sable', 'sableux'"
    S-SC: "should contain 'sable peu argileux'"
    S-SM: "should contain 'sable peu limoneux'"
    SC: "should contain 'sable argileux'"
    SC-SM: "should contain 'sable limono-argileux'"
    SM: "should contain 'sable limoneux'"
    SP: "should contain 'sable mal gradué', 'sable moyen', 'sable grossier'"
    SP-SC: "should contain 'sable mal gradué avec argile'"
    SP-SM: "should contain 'sable mal gradué avec limon', 'sable moyen, limoneux'"
    SW: "should contain 'sable bien gradué'"
    SW-SC: "should contain 'sable bien gradué avec argile'"
    SW-SM: "should contain 'sable bien gradué avec limon'"
    Bl: "should contain 'bloc'"
    FELS: "should contain 'rocher', 'marne', 'marno', 'molasse', 'gypse', 'schistes'"
    kA: "should contain 'sans indication'"
    kunst: "should contain 'remplissage artificiel', 'bitume', 'bitumineux'"
    Pt: "should contain 'tourbe'"
    St: "should contain 'pierre'"
    St-Bl: "should contain 'pierre et bloc'"
  it:
    CH: "should contain 'argilla grassa', 'argilla molto plastica'"
    CL: "should contain 'argilla limosa', 'argilla poco plastica'"
    CL-ML: "should contain 'limo argilloso', 'miscela argilla-limo'"
    CM: "should contain 'argilla magra', 'argilla scarsamente plastica'"
    G: "should contain 'ghiaia', 'ghiaia grossa', 'ghiaia fine'"
    G-GC: "should contain 'ghiaia leggermente argillosa'"
    G-GM: "should contain 'ghiaia leggermente limosa'"
    GC: "should contain 'ghiaia argillosa'"
    GC-GM: "should contain 'ghiaia limoso-argillosa'"
    GM: "should contain 'ghiaia limosa'"
    GP: "should contain 'ghiaia mal classata', 'ghiaia uniforme'"
    GP-GC: "should contain 'ghiaia mal classata con argilla'"
    GP-GM: "should contain 'ghiaia mal classata con limo'"
    GW: "should contain 'ghiaia ben classata'"
    GW-GC: "should contain 'ghiaia ben classata con argilla'"
    GW-GM: "should contain 'ghiaia ben classata con limo'"
    MH: "should contain 'limo elastico', 'limo molto plastico'"
    ML: "should contain 'limo', 'limo poco plastico'"
    OH: "should contain 'limo organico', 'limo ricco di humus'"
    OL: "should contain 'argilla organica', 'argilla torbosa'"
    S: "should contain 'sabbia', 'sabbia fine, media, grossa'"
    S-SC: "should contain 'sabbia leggermente argillosa'"
    S-SM: "should contain 'sabbia leggermente limosa'"
    SC: "should contain 'sabbia argillosa'"
    SC-SM: "should contain 'sabbia limo-argillosa'"
    SM: "should contain 'sabbia limosa'"
    SP: "should contain 'sabbia mal classata', 'sabbia uniforme'"
    SP-SC: "should contain 'sabbia mal classata con argilla'"
    SP-SM: "should contain 'sabbia mal classata con limo'"
    SW: "should contain 'sabbia ben classata'"
    SW-SC: "should contain 'sabbia ben classata con argilla'"
    SW-SM: "should contain 'sabbia ben classata con limo'"
    Bl: "should contain 'blocco'"
    FELS: "should contain 'roccia', 'arenaria', 'scisto', 'gesso', 'calcare', 'marl'"
    kA: "should contain 'senza indicazioni', 'non specificato'"
    kunst: "should contain 'riempimento artificiale', 'materiale di riporto'"
    Pt: "should contain 'torba'"
    St: "should contain 'pietra', 'pietre'"
    St-Bl: "should contain 'pietre e blocchi'"