default_language: "de"
supported_language: ["de","fr","en","it"]
uscs_patterns:
  de:
    kunst: "künstliche Auffüllung"
    Bl: "Block (Bl)"
    GP: "schlecht abgestufter Kies (GP)"
    CH: "fetter Ton (CH)"
    CM: "magerer Ton (CM)"
    CL: "siltiger Ton (CL)"
    CL-ML: "toniger Silt (CL-ML)"
    G: "Kies (G)"
    S: "Sand (S)"
    GW-GC: "gut abgestufter Kies mit Ton (GW-GC)"
    Pt: "Torf (Pt)"
    ML: "Silt (ML)"
    GM: "siltiger Kies (GM)"
    kA: "keine Angabe"
    FELS: "Fels"
    SC: "toniger Sand (SC)"
    S-SM: "schwach siltiger Sand (S-SM)"
    SM: "siltiger Sand (SM)"
    SP: "schlecht abgestufter Sand (SP)"
    SP-SC: "schlecht abgestufter Sand mit Ton (SP-SC)"
    SP-SM: "schlecht abgestufter Sand mit Silt (SP-SM)"
    SW: "gut abgestufter Sand (SW)"
    SW-SC: "gut abgestufter Sand mit Ton (SW-SC)"
    SW-SM: "gut abgestufter Sand mit Silt (SW-SM)"
    G-GC: "schwach toniger Kies (G-GC)"
    G-GM: "schwach siltiger Kies (G-GM)"
    St: "Stein (St)"
    St-Bl: "Steine und Blöcke (St-Bl)"
    OH: "organischer Silt (OH)"
    OL: "organischer Ton (OL)"
    S-SC: "schwach toniger Sand (S-SC)"
    SC-SM: "siltiger bis toniger Sand (SC-SM)"
    GC: "toniger Kies (GC)"
    GC-GM: "siltiger bis toniger Kies (GC-GM)"
    GP-GC: "schlecht abgestufter Kies mit Ton (GP-GC)"
    GP-GM: "schlecht abgestufter Kies mit Silt (GP-GM)"
    GW: "gut abgestufter Kies (GW)"
    GW-GM: "gut abgestufter Kies mit Silt (GW-GM)"
    MH: "elastischer Silt (MH)"
  fr:
    kunst: "remplissage artificiel"
    Bl: "bloc (Bl)"
    GP: "gravier mal gradué (GP)"
    CH: "argile grasse (CH)"
    CM: "argile maigre (CM)"
    CL: "argile limoneuse (CL)"
    CL-ML: "limon argileux (CL-ML)"
    G: "gravier (G)"
    S: "sable (S)"
    GW-GC: "gravier bien gradué avec argile (GW-GC)"
    Pt: "tourbe (Pt)"
    ML: "limon (ML)"
    GM: "gravier limoneux (GM)"
    kA: "sans indication"
    FELS: "rocher"
    SC: "sable argileux (SC)"
    S-SM: "sable peu limoneux (S-SM)"
    SM: "sable limoneux (SM)"
    SP: "sable mal gradué (SP)"
    SP-SC: "sable mal gradué avec argile (SP-SC)"
    SP-SM: "sable mal gradué avec limon (SP-SM)"
    SW: "sable bien gradué (SW)"
    SW-SC: "sable bien gradué avec argile (SW-SC)"
    SW-SM: "sable bien gradué avec limon (SW-SM)"
    G-GC: "gravier peu argileux (G-GC)"
    G-GM: "gravier peu limoneux (G-GM)"
    St: "pierre (St)"
    St-Bl: "pierre et bloc (St-Bl)"
    OH: "limon organique (OH)"
    OL: "argile organique (OL)"
    S-SC: "sable peu argileux (S-SC)"
    SC-SM: "sable limono-argileux (SC-SM)"
    GC: "gravier argileux (GC)"
    GC-GM: "gravier limono-argileux (GC-GM)"
    GP-GC: "gravier mal gradué avec argile (GP-GC)"
    GP-GM: "gravier mal gradué avec limon (GP-GM)"
    GW: "gravier bien gradué (GW)"
    GW-GM: "gravier bien gradué avec limon (GW-GM)"
    MH: "limon élastique (MH)"

  en:
    kunst: "artificial landfill"
    Bl: "boulder (Bl)"
    GP: "poorly graded gravel (GP)"
    CH: "fat clay (CH)"
    CM: "lean clay (CM)"
    CL: "silty clay (CL)"
    CL-ML: "clayey silt (CL-ML)"
    G: "gravel (G)"
    S: "sand (S)"
    GW-GC: "well-graded gravel with clay (GW-GC)"
    Pt: "peat (Pt)"
    ML: "silt (ML)"
    GM: "silty gravel (GM)"
    kA: "not specified"
    FELS: "bed rock"
    SC: "clayey sand (SC)"
    S-SM: "slightly silty sand (S-SM)"
    SM: "silty sand (SM)"
    SP: "poorly graded sand (SP)"
    SP-SC: "poorly graded sand with clay (SP-SC)"
    SP-SM: "poorly graded sand with silt (SP-SM)"
    SW: "well-graded sand (SW)"
    SW-SC: "well-graded sand with clay (SW-SC)"
    SW-SM: "well-graded sand with silt (SW-SM)"
    G-GC: "slightly clayey gravel (G-GC)"
    G-GM: "slightly silty gravel (G-GM)"
    St: "cobbles (St)"
    St-Bl: "cobbles and boulders (St-Bl)"
    OH: "organic silt (OH)"
    OL: "organic clay (OL)"
    S-SC: "slightly clayey sand (S-SC)"
    SC-SM: "silty, clayey sand (SC-SM)"
    GC: "clayey gravel (GC)"
    GC-GM: "silty, clayey gravel (GC-GM)"
    GP-GC: "poorly graded gravel with clay (GP-GC)"
    GP-GM: "poorly graded gravel with silt (GP-GM)"
    GW: "well-graded gravel (GW)"
    GW-GM: "well-graded gravel with silt (GW-GM)"
    MH: "elastic silt (MH)"
  it:
    kunst: "riempimento artificiale"
    Bl: "blocco (Bl)"
    GP: "ghiaia mal classata (GP)"
    CH: "argilla grassa (CH)"
    CM: "argilla magra (CM)"
    CL: "argilla limosa (CL)"
    CL-ML: "limo argilloso (CL-ML)"
    G: "ghiaia (G)"
    S: "sabbia (S)"
    GW-GC: "ghiaia ben con argilla (GW-GC)"
    Pt: "torba (Pt)"
    ML: "limo (ML)"
    GM: "ghiaia limosa (GM)"
    kA: "senza indicazioni"
    FELS: "roccia"
    SC: "sabbia argillosa (SC)"
    S-SM: "sabbia leggermente limosa (S-SM)"
    SM: "sabbia limosa (SM)"
    SP: "sabbia mal classata (SP)"
    SP-SC: "sabbia mal classata con argilla (SP-SC)"
    SP-SM: "sabbia mal classata con limo (SP-SM)"
    SW: "sabbia ben classata (SW)"
    SW-SC: "sabbia ben classata con argilla (SW-SC)"
    SW-SM: "sabbia ben classata con limo (SW-SM)"
    G-GC: "ghiaia leggermente argillosa (G-GC)"
    G-GM: "ghiaia leggermente limosa (G-GM)"
    St: "pietra (St)"
    St-Bl: "pietre e blocchi (St-Bl)"
    OH: "limo organico (OH)"
    OL: "argilla organica (OL)"
    S-SC: "sabbia leggermente argillosa (S-SC)"
    SC-SM: "sabbia limo argillosa (SC-SM)"
    GC: "ghiaia argillosa (GC)"
    GC-GM: "ghiaia limoso argillosa (GC-GM)"
    GP-GC: "ghiaia mal classata con argilla (GP-GC)"
    GP-GM: "ghiaia mal classata con limo (GP-GM)"
    GW: "ghiaia ben classata (GW)"
    GW-GM: "ghiaia ben con limo (GW-GM)"
    MH: "limo elastico (MH)"

