default_language: de
supported_language: [de,fr,en,it]
uscs_patterns:
  de:
    CH: should contain 'fetter Ton'
    CL: should contain 'siltiger Ton' or'Lehm' or 'Feinsand'
    CL-ML: should contain toniger Silt or 'tonig-sandiger Silt'
    CM: should contain 'magerer Ton'
    G: should contain 'Kies', 'Kiessand'
    G-GC: should contain 'schwach toniger Kies', 'leicht toniger Kies'
    G-GM: should contain 'schwach siltiger Kies', 'leicht siltiger Kies'
    GC: should contain 'toniger Kies', 'Kies, Lehm'
    GC-GM: should contain 'siltiger bis toniger Kies'
    GM: should contain 'siltiger Kies'
    GP: should contain 'schlecht abgestufter Kies', 'grober Kies', 'mittelgrober Kies', 'sandiger Feinkies', 'Grobkies', 'Feinkies'
    GP-GC: should contain 'schlecht abgestufter Kies mit Ton'
    GP-GM: should contain 'schlecht abgestufter Kies mit Silt', 'siltiger Grobkies', 'siltiger Mittelkies', 'siltiger Feinkeis'
    GW: should contain 'gut abgestufter Kies'
    GW-GC: should contain 'gut abgestufter Kies mit Ton'
    GW-GM: should contain 'gut abgestufter Kies mit Silt'
    MH: should contain 'elastischer Silt'
    ML: should contain 'Silt', 'Siltsand', 'Silt, Kies', 'sandiger Lehm'
    OH: should contain 'organischer Silt', 'Humus', 'humoser Silt'
    OL: should contain 'organischer Ton', 'Humus und Sand'
    S: should contain 'Sand', 'Sand, Kies'
    S-SC: should contain 'schwach toniger Sand', 'leicht toniger Sand'
    S-SM: should contain 'schwach siltiger Sand', 'leicht siltiger Sand', 'leicht siltiger Feinsand', 'leicht siltiger Mittelsand'
    SC: should contain 'toniger Sand', 'lehmiger Sand'
    SC-SM: should contain 'siltiger, toniger Sand', 'Sand, verlehmt, siltig'
    SM: should contain 'siltiger Sand'
    SP: should contain 'schlecht abgestufter Sand', 'grobkörniger Sand', 'mittelkörniger Sand', 'feinkiesiger Mittelsand'
    SP-SC: should contain 'schlecht abgestufter Sand mit Ton', 'Feinsand, Lehm', 'toniger Feinsand'
    SP-SM: should contain 'schlecht abgestufter Sand mit Silt', 'siltiger Feinsand', 'siltiger Mittelsand', 'siltiger Grobsand', 'siltiger Feinkies'
    SW: should contain 'gut abgestufter Sand', 'Sand, Kies, Silt'
    SW-SC: should contain 'gut abgestufter Sand mit Ton'
    SW-SM: should contain 'gut abgestufter Sand mit Silt', 'Grobmittelsand, siltig', 'Feinmittelsand, siltig'
    Bl: should contain 'Block'
    FELS: should contain 'Fels', 'Sandstein', 'Tonstein', 'Mergel', 'Molasse', 'Kalk', 'Sandsteinbrocken', 'Sandsteinmolasse', 'Gips'
    kA: should contain 'keine Angabe', 'unbekannt', 'nicht beschrieben'
    kunst: should contain 'Auffüllung', 'Aufschüttung', 'Beton'
    Pt: should contain 'Torf'
    St: should include Stein
    St-Bl: should incliude 'Steine und Blöcke'
  fr:
    CH: should contain 'argile grasse'
    CL: should contain 'argile limoneuse', 'argile', 'argileux'
    CL-ML: should contain 'limon argileux'
    CM: should contain 'argile maigre'
    G: should contain 'gravier'
    G-GC: should contain 'gravier peu argileux'
    G-GM: should contain 'gravier peu limoneux'
    GC: should contain 'gravier argileux'
    GC-GM: should contain 'gravier limono-argileux'
    GP: should contain 'gravier mal gradué', 'gravier moyen', 'gravier grossier'
    GP-GC: should contain 'gravier mal gradué avec argile'
    GP-GM: should contain 'gravier mal gradué avec limon', 'gravier moyen, limoneux', 'gravier grossier, limoneux'
    GM: should contain 'gravier limoneux'
    GW: should contain 'gravier bien gradué'
    GW-GM: should contain 'gravier bien gradué avec limon', 'gravier, galets, limoneux', 'gravier, éléments roulés, limoneux'
    GW-GC: should contain 'gravier bien gradué avec argile'
    MH: should contain 'limon élastique'
    ML: should contain 'limon'
    OH: should contain 'limon organique', 'végétal'
    OL: should contain 'argile organique'
    S: should contain 'sable', 'sableux'
    S-SC: should contain 'sable peu argileux'
    S-SM: should contain 'sable peu limoneux'
    SC: should contain 'sable argileux'
    SC-SM: should contain 'sable limono-argileux'
    SM: should contain 'sable limoneux'
    SP: should contain 'sable mal gradué', 'sable moyen', 'sable grossier'
    SP-SC: should contain 'sable mal gradué avec argile'
    SP-SM: should contain 'sable mal gradué avec limon', 'sable moyen, limoneux'
    SW: should contain 'sable bien gradué'
    SW-SC: should contain 'sable bien gradué avec argile'
    SW-SM: should contain 'sable bien gradué avec limon'
    Bl: should contain 'bloc'
    FELS: should contain 'rocher', 'marne', 'marno', 'molasse', 'gypse', 'schistes'
    kA: should contain 'sans indication'
    kunst: should contain 'remplissage artificiel', 'bitume', 'bitumineux'
    Pt: should contain 'tourbe'
    St: should contain 'pierre'
    St-Bl: should contain 'pierre et bloc'

  en:
    kunst: should contain 'artificial landfill'
    Bl: should contain 'boulder'
    GP: should contain 'poorly graded gravel'
    CH: should contain 'fat clay'
    CM: should contain 'lean clay'
    CL: should contain 'silty clay'
    CL-ML: should contain 'clayey silt'
    G: should contain 'gravel'
    S: should contain 'sand'
    GW-GC: should contain 'well-graded gravel with clay'
    Pt: should contain 'peat'
    ML: should contain 'silt'
    GM: should contain 'silty gravel'
    kA: should contain 'not specified'
    FELS: should contain 'bed rock'
    SC: should contain 'clayey sand'
    S-SM: should contain 'slightly silty sand'
    SM: should contain 'silty sand'
    SP: should contain 'poorly graded sand'
    SP-SC: should contain 'poorly graded sand with clay'
    SP-SM: should contain 'poorly graded sand with silt'
    SW: should contain 'well-graded sand'
    SW-SC: should contain 'well-graded sand with clay'
    SW-SM: should contain 'well-graded sand with silt'
    G-GC: should contain 'slightly clayey gravel'
    G-GM: should contain 'slightly silty gravel'
    St: should contain 'cobbles'
    St-Bl: should contain 'cobbles and boulders'
    OH: should contain 'organic silt'
    OL: should contain 'organic clay'
    S-SC: should contain 'slightly clayey sand'
    SC-SM: should contain 'silty, clayey sand'
    GC: should contain 'clayey gravel'
    GC-GM: should contain 'silty, clayey gravel'
    GP-GC: should contain 'poorly graded gravel with clay'
    GP-GM: should contain 'poorly graded gravel with silt'
    GW: should contain 'well-graded gravel'
    GW-GM: should contain 'well-graded gravel with silt'
    MH: should contain 'elastic silt'
  it:
    kunst: should contain 'riempimento artificiale'
    Bl: should contain 'blocco'
    GP: should contain 'ghiaia mal classata'
    CH: should contain 'argilla grassa'
    CM: should contain 'argilla magra'
    CL: should contain 'argilla limosa'
    CL-ML: should contain 'limo argilloso'
    G: should contain 'ghiaia'
    S: should contain 'sabbia'
    GW-GC: should contain 'ghiaia ben con argilla'
    Pt: should contain 'torba'
    ML: should contain 'limo'
    GM: should contain 'ghiaia limosa'
    kA: should contain 'senza indicazioni'
    FELS: should contain 'roccia'
    SC: should contain 'sabbia argillosa'
    S-SM: should contain 'sabbia leggermente limosa'
    SM: should contain 'sabbia limosa'
    SP: should contain 'sabbia mal classata'
    SP-SC: should contain 'sabbia mal classata con argilla'
    SP-SM: should contain 'sabbia mal classata con limo'
    SW: should contain 'sabbia ben classata'
    SW-SC: should contain 'sabbia ben classata con argilla'
    SW-SM: should contain 'sabbia ben classata con limo'
    G-GC: should contain 'ghiaia leggermente argillosa'
    G-GM: should contain 'ghiaia leggermente limosa'
    St: should contain 'pietra'
    St-Bl: should contain 'pietre e blocchi'
    OH: should contain 'limo organico'
    OL: should contain 'argilla organica'
    S-SC: should contain 'sabbia leggermente argillosa'
    SC-SM: should contain 'sabbia limo argillosa'
    GC: should contain 'ghiaia argillosa'
    GC-GM: should contain 'ghiaia limoso argillosa'
    GP-GC: should contain 'ghiaia mal classata con argilla'
    GP-GM: should contain 'ghiaia mal classata con limo'
    GW: should contain 'ghiaia ben classata'
    GW-GM: should contain 'ghiaia ben con limo'
    MH: should contain 'limo elastico'