default_language: "de"
supported_language: ["de", "fr", "en", "it"]
patterns:
  en:
    Amphibolite: ["amphibolite"]
    Migmatite: ["migmatite", "Biotite-Plagioclase-Gneiss"]
    Andesite: ["andesite"]
    Aplite: ["aplite", "aplitic rock"]
    Basalt: ["basalt"]
    Basanite: ["basanite"]
    Bentonite: ["bentonite"]
    Claystone: ["claystone", "shale"]
    Breccia: ["breccia"]
    Rock: ["rock", "consolidated rock, stone"]
    Rhyolite: ["rhyolite"]
    Psephite: ["psephite"]
    Tuffite: ["tuffite", "tuffitic rock"]
    Cataclastite: ["cataclastite"]
    Pelite: ["pelite"]
    Conglomerate: ["conglomerate", "puddingstone"]
    Dacite: ["dacite"]
    Diorite: ["diorite"]
    Monzonite: ["monzonite"]
    Dolostone: ["dolostone"]
    Eclogite: ["eclogite"]
    Evaporite: ["evaporite", "evaporitic rock", "anhydrite"]
    Foidite: ["foidite"]
    Foidolite: ["foidolite"]
    Gabbro: ["gabbro"]
    Mylonite: ["mylonite"]
    Gneiss: ["gneiss"]
    Granite: ["granite"]
    Granodiorite: ["granodiorite"]
    Granulite: ["granulite"]
    Psammite: ["psammite"]
    Schist: ["schist"]
    Syenite: ["syenite"]
    Granofels: ["granofels", "fels"]
    Peridotite: ["peridotite"]
    Pyroxenite: ["pyroxenite"]
    Granophyre: ["granophyre", "granophyric rock"]
    Hornfels: ["hornfels"]
    Ignimbrite: ["ignimbrite"]
    Kakirite: ["kakirite"]
    Latite: ["latite", "trachyandesite"]
    Limestone: ["limestone"]
    Marble: ["marble"]
    Marlstone: ["marlstone", "marl"]
    Phyllite: ["phyllite"]
    Pegmatite: ["pegmatite", "pegmatitic rock"]
    Siltstone: ["siltstone"]
    Serpentinite: ["serpentinite"]
    Phonolite: ["phonolite"]
    Prasinite: ["prasinite"]
    Sandstone: ["sandstone"]
    Pseudotachyllite: ["pseudotachyllite"]
    Quartzite: ["quartzite"]
    Rauwacke: ["rauwacke", "cellular dolostone"]
    Rodingite: ["rodingite"]
    Tonalite: ["tonalite"]
    Tephrite: ["tephrite"]
    Trachyte: ["trachyte"]
    kA: ["not specified"]
    Unconsolidated: ["clay", "silt", "gravel", "peat", "sand", "pebble", "loam"]
    #Unconsolidated: ["clay", "silt", "gravel", "peat", "sand", "pebble", "loam"]
  fr:
    Amphibolite: ["amphibolite"]
    Migmatite: ["migmatite"]
    Andesite: ["andésite"]
    Aplite: ["aplite"]
    Basalt: ["basalte"]
    Basanite: ["basanite"]
    Bentonite: ["bentonite"]
    Claystone: ["argilite"]
    Breccia: ["brèche"]
    Rock: ["roche", "roche consolidée"]
    Rhyolite: ["rhyolite"]
    Psephite: ["pséphite"]
    Tuffite: ["tuffite"]
    Cataclastite: ["cataclastite"]
    Pelite: ["pélite"]
    Conglomerate: ["conglomérat", "poudingue"]
    Dacite: ["dacite"]
    Diorite: ["diorite"]
    Monzonite: ["monzonite"]
    Dolostone: ["dolomie"]
    Eclogite: ["éclogite",]
    Evaporite: ["évaporite", "roche évaporitique", "Anhydrite", "sel"]
    Foidite: ["foïdite"]
    Foidolite: ["foïdolite"]
    Gabbro: ["gabbro"]
    Mylonite: ["mylonite"]
    Gneiss: ["gneiss"]
    Granite: ["granite"]
    Granodiorite: ["granodiorite"]
    Granulite: ["granulite"]
    Psammite: ["psammite"]
    Schist: ["schiste"]
    Syenite: ["syénite"]
    Granofels: ["granofels", "fels"]
    Peridotite: ["péridotite"]
    Pyroxenite: ["pyroxénite"]
    Granophyre: ["granophyre"]
    Hornfels: ["cornéenne", "roche du métamorphisme de contact"]
    Ignimbrite: ["ignimbrite"]
    Kakirite: ["kakirite"]
    Latite: ["latite", "trachyandésite"]
    Limestone: ["calcaire"]
    Marble: ["marbre"]
    Marlstone: ["marne"]
    Phyllite: ["phyllite"]
    Pegmatite: ["pegmatite"]
    Siltstone: ["siltite"]
    Serpentinite: ["serpentinite"]
    Phonolite: ["phonolite"]
    Prasinite: ["prasinite"]
    Sandstone: ["grès"]
    Pseudotachyllite: ["pseudotachyllite"]
    Quartzite: ["quartzite"]
    Rauwacke: ["cornieule"]
    Rodingite: ["rodingite"]
    Tonalite: ["tonalite"]
    Tephrite: ["téphrite"]
    Trachyte: ["trachyte"]
    kA: ["sans indication"]
    Unconsolidated: ["argile", "silt", "tourbe", "sable", "gravier", "limon"]
  de:
    Amphibolite: ["Amphibolit"]
    Migmatite: ["Migmatit"]
    Andesite: ["Andesit"]
    Aplite: ["Aplit"]
    Basalt: ["Basalt"]
    Basanite: ["Basanit"]
    Bentonite: ["Bentonit"]
    Claystone: ["Tonstein", "Tonlage", "Tonschiefer"]
    Breccia: ["Brekzie"]
    Rock: ["Gestein", "Festgestein"]
    Rhyolite: ["Rhyolith"]
    Psephite: ["Psephit"]
    Tuffite: ["Tuffit"]
    Cataclastite: ["Kataklasit"]
    Pelite: ["Pelit", "Schlammstein"]
    Conglomerate: ["Konglomerat", "Nagelfluh"]
    Dacite: ["Dazit"]
    Diorite: ["Diorit"]
    Monzonite: ["Monzonit"]
    Dolostone: ["Dolomitstein", "Dolomit"]
    Eclogite: ["Eklogit"]
    Evaporite: ["Evaporit", "Salzgestein, Evaporitgestein", "Anhydrit", "Steinsalz"]
    Foidite: ["Foidit"]
    Foidolite: ["Foidolit"]
    Gabbro: ["Gabbro"]
    Mylonite: ["Mylonit"]
    Gneiss: ["Gneis"]
    Granite: ["Granit"]
    Granodiorite: ["Granodiorit"]
    Granulite: ["Granulit"]
    Psammite: ["Psammit"]
    Schist: ["Schiefer"]
    Syenite: ["Syenit"]
    Granofels: ["Granofels", "Fels"]
    Peridotite: ["Peridotit"]
    Pyroxenite: ["Pyroxenit"]
    Granophyre: ["Granophyr"]
    Hornfels: ["Hornfels", "Gestein der Kontaktmetamorphose"]
    Ignimbrite: ["Ignimbrit"]
    Kakirite: ["Kakirit"]
    Latite: ["Latit", "Trachyandesit"]
    Limestone: ["Kalkstein"]
    Marble: ["Marmor"]
    Marlstone: ["Mergelstein", "Kalkmergelstein", "Tonmergelstein", "Siltmergelstein", "Mergel(stein)"]
    Phyllite: ["Phyllit"]
    Pegmatite: ["Pegmatit"]
    Siltstone: ["Siltstein", "Ton-Silstein", "Silt-Feinsandstein", "toniger Siltstein"]
    Serpentinite: ["Serpentinit"]
    Phonolite: ["Phonolith"]
    Prasinite: ["Prasinit"]
    Sandstone: ["Sandstein", "Grobsandstein", "Mittelgrobsandstein", "Kalksandstein", "Mittelsandstein", "Feinmittelsandstein", "Feinstandstein"]
    Pseudotachyllite: ["Pseudotachyllit"]
    Quartzite: ["Quarzit"]
    Rauwacke: ["Rauwacke", "Zellendolomit"]
    Rodingite: ["Rodingit"]
    Tonalite: ["Tonalit"]
    Tephrite: ["Tephrit"]
    Trachyte: ["Trachyt"]
    kA: ["keine Angabe", "unbekannt, nicht beschrieben"]
    # Unconsolidated: ["Ton", "Mergel", "Silt", "Torf", "Sand", "Kies", "Lehm"]
    Unconsolidated: ["Kies", "Torf", "Sand", "Humus", "Lehm"]
  it:
    Amphibolite: ["anfibolite"]
    Migmatite: ["migmatite"]
    Andesite: ["andesite"]
    Aplite: ["aplite"]
    Basalt: ["basalto"]
    Basanite: ["basanite"]
    Bentonite: ["bentonite"]
    Claystone: ["argillite"]
    Breccia: ["breccia"]
    Rock: ["roccia"]
    Rhyolite: ["riolite"]
    Psephite: ["psefite"]
    Tuffite: ["tufite"]
    Cataclastite: ["cataclastite"]
    Pelite: ["pelite"]
    Conglomerate: ["conglomerato", "puddinga"]
    Dacite: ["dacite"]
    Diorite: ["diorite"]
    Monzonite: ["monzonite"]
    Dolostone: ["dolomia"]
    Eclogite: ["eclogite"]
    Evaporite: ["evaporite", "roccia evaporitica"]
    Foidite: ["foidite"]
    Foidolite: ["foidolite"]
    Gabbro: ["gabbro"]
    Mylonite: ["milonite"]
    Gneiss: ["gneiss"]
    Granite: ["granito"]
    Granodiorite: ["granodiorite"]
    Granulite: ["granulite"]
    Psammite: ["psammite"]
    Schist: ["scisto"]
    Syenite: ["sienite"]
    Granofels: ["granofels"]
    Peridotite: ["peridotite"]
    Pyroxenite: ["pirossenite"]
    Granophyre: ["granofiro"]
    Hornfels: ["cornubianite", "hornfels"]
    Ignimbrite: ["ignimbrite"]
    Kakirite: ["cachirite"]
    Latite: ["latite"]
    Limestone: ["calcare"]
    Marble: ["marmo"]
    Marlstone: ["marna"]
    Phyllite: ["fillite"]
    Pegmatite: ["pegmatite"]
    Siltstone: ["siltite"]
    Serpentinite: ["serpentinite"]
    Phonolite: ["fonolite"]
    Prasinite: ["prasinite"]
    Sandstone: ["arenaria"]
    Pseudotachyllite: ["pseudotachilite"]
    Quartzite: ["quarzite"]
    Rauwacke: ["cargnola"]
    Rodingite: ["rodingite"]
    Tonalite: ["tonalite"]
    Tephrite: ["tefrite"]
    Trachyte: ["trachite"]
    kA: ["senza indicazioni"]
    Unconsolidated: ["argilla", "marna", "silt", "torba", "sabbia", "ghiaia", "limo"]
