tables:
  # Line length requirements for meaningful table detection
  min_line_length: 20

  # Angle requirements
  angle_tolerance: 10

  # Connection threshold for line groups
  connection_threshold: 8.0

  # Confidence threshold for table detection
  min_confidence: 0.45

  # Table area score for confidence calculation
  area_scoring:
    area_weights: 0.2
    min_table_area_ratio: 0.4

  # Line score for confidence calculation
  line_scoring:
    line_weights: 0.5
    max_n_lines_bonus: 90

  # Text bonus scoring for confidence calculation
  text_scoring:
    text_weights: 0.3
    text_presence_weight: 0.01

# Strip log detection parameters
strip_logs:
  # Penalty for text within strip log region
  text_penalty: 0.15

  # Minimum confidence threshold for strip log detection
  min_confidence: 0.5

  # Minimum number of horizontal lines required
  min_horizontal_lines: 3

  # Minimum structure width
  min_width: 15

  # Minimum number of circles required
  min_circle_count: 20

  # Minimum aspect ratio (height/width) for strip logs
  aspect:
    min_aspect_ratio: 1
    aspect_weight: 0.2

  # Minimum horizontal line density
  line_density:
    min_horizontal_density: 20
    line_density_weight: 0.3

  # Minimum circle density
  circle_density:
    min_circle_density: 40
    circle_weight: 0.5