# Line requirements for meaningful table detection, number of lines and minimum length
min_total_lines: 3
min_line_length: 50

# Angle requirements - degrees of tolerance for classification for horizontal/vertical lines
angle_tolerance: 5.0

# Distance from page edge to ignore "scan artifacts"
page_boundary_margin: 5

# Confidence threshold for table detection
min_confidence: 0.6

# Area bonus for confidence calculation
area_scoring:
  max_area_bonus: 0.4
  min_table_area_ratio: 0.8

# Line bonus for confidence calculation
line_scoring:
  max_line_bonus: 0.2
  max_n_lines_bonus: 120

# Text bonus scoring for confidence calculation
text_scoring:
  max_text_bonus: 0.4        # Maximum bonus from text presence (0.0 - 1.0)
  text_presence_weight: 0.002 # Weight per text line found within table (e.g., 0.02 * 10 lines = 0.3 max)
