# Line requirements for meaningful table detection, number of lines and minimum length
min_total_lines: 4
min_line_length: 50

# Structure requirements - minimum table area as ratio of page, minimum confidence
min_table_area_ratio: 0.30
min_confidence: 0.6

# Angle requirements - degrees of tolerance for classification for horizontal/vertical lines
angle_tolerance: 10.0

# Distance from page edge to ignore "scan artifacts"
page_boundary_margin: 10.0
