dummy:
  accessory_components: null
  alteration_degree_consolidated: null
  alteration_degree_unconsolidated: null
  borehole_type: null
  cementation: null
  color_consolidated: null
  color_unconsolidated: null
  debris: null
  en_main: null
  en_secondary: null
  grain_angularity: null
  grain_shape: null
  lithology: null
  mineral_components: null
  organic_components: null
  uscs: null
baseline:
  accessory_components: null
  alteration_degree_consolidated: null
  alteration_degree_unconsolidated: null
  borehole_type: null
  cementation: null
  color_consolidated: null
  color_unconsolidated: null
  debris: null
  en_main: null
  en_secondary: null
  grain_angularity: null
  grain_shape: null
  lithology: baseline/baseline_config_lithology.yml
  mineral_components: null
  organic_components: null
  uscs: baseline/baseline_config_uscs.yml
bert:
  accessory_components: bert/bert_config_accessory_components.yml
  alteration_degree_consolidated: bert/bert_config_alteration_degree_c2a.yml
  alteration_degree_unconsolidated: bert/bert_config_alteration_degree_u2a.yml
  borehole_type: bert/bert_config_borehole_type.yml
  cementation: bert/bert_config_cementation.yml
  color_consolidated: bert/bert_config_color_c2a.yml
  color_unconsolidated: bert/bert_config_color_u2a.yml
  debris: bert/bert_config_debris.yml
  en_main: bert/bert_config_en_main.yml
  en_secondary: bert/bert_config_en_secondary.yml
  grain_angularity: bert/bert_config_grain_angularity.yml
  grain_shape: bert/bert_config_grain_shape.yml
  lithology: bert/bert_config_lithology.yml
  mineral_components: bert/bert_config_mineral_components.yml
  organic_components: bert/bert_config_organic_components.yml
  uscs: bert/bert_config_uscs.yml
bedrock:
  accessory_components: bedrock/bedrock_config_accessory_components.yml
  alteration_degree_consolidated: bedrock/bedrock_config_alteration_degree.yml
  alteration_degree_unconsolidated: bedrock/bedrock_config_alteration_degree.yml
  borehole_type: null
  cementation: bedrock/bedrock_config_cementation.yml
  color_consolidated: bedrock/bedrock_config_color.yml
  color_unconsolidated: bedrock/bedrock_config_color.yml
  debris: bedrock/bedrock_config_debris.yml
  en_main: bedrock/bedrock_config_en_main.yml
  en_secondary: bedrock/bedrock_config_en_secondary.yml
  grain_angularity: bedrock/bedrock_config_grain_angularity.yml
  grain_shape: bedrock/bedrock_config_grain_shape.yml
  lithology: bedrock/bedrock_config_lithology.yml
  mineral_components: bedrock/bedrock_config_mineral_components.yml
  organic_components: bedrock/bedrock_config_organic_components.yml
  uscs: bedrock/bedrock_config_uscs.yml
