FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04:latest

WORKDIR /tmp/build
COPY requirements-azureml.txt .
RUN pip install --no-cache-dir -r requirements-azureml.txt

# azureml-mlflow is not in pyproject.toml but needed for experiment tracking
RUN pip install --no-cache-dir azureml-mlflow
