name: pipeline_run

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  pipeline_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"
      - name: Install dependencies and run pipeline
        shell: bash
        run: |
          uv sync
          echo "Running pipeline"
          uv run boreholes-extract-all -l -i example/example_borehole_profile.pdf -o example/ -p example/predictions.json -m example/metadata.json -g example/example_groundtruth.json -pa all

          echo "Running scoring script"
          uv run boreholes-score --ground-truth-path example/example_groundtruth.json --predictions-path example/predictions.json
