name: Pre-release

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-pre-release:
    runs-on: ubuntu-latest
    name: Build and push Docker image and create a new GitHub pre-release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set environment variables
        run: |
          echo VERSION=$(cat VERSION).$GITHUB_RUN_NUMBER >> $GITHUB_ENV
          echo BASE_IMAGE_NAME=$REGISTRY/$(echo ${GITHUB_REPOSITORY,,}) >> $GITHUB_ENV
          echo COMMITED_AT=$(git show -s --format=%cI `git rev-parse HEAD`) >> $GITHUB_ENV
      - name: Collect Docker image metadata (api)
        id: meta-api
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.BASE_IMAGE_NAME }}-api
          labels: |
            org.opencontainers.image.created=${{ env.COMMITED_AT }}
            org.opencontainers.image.version=v${{ env.VERSION }}
            org.opencontainers.image.authors=Stijn Vermeeren <stijn.vermeeren@swisstopo.ch>
          flavor: |
            latest=false
          tags: |
            type=edge
            type=semver,pattern=v{{version}},value=${{ env.VERSION }}

      - name: Log in to the GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner  }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image (api)
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
          tags: ${{ steps.meta-api.outputs.tags }}
          labels: ${{ steps.meta-api.outputs.labels }}
          cache-from: type=registry,ref=${{ env.BASE_IMAGE_NAME }}-api:edge
          cache-to: type=inline
      
      # Check final image size
      - name: Check Docker image size and layers
        run: |
          echo "=== FINAL IMAGE SIZE ==="
          docker images ${{ env.BASE_IMAGE_NAME }}-api:v${{ env.VERSION }}
          echo ""
          echo "=== DOCKER HISTORY (layer sizes) ==="
          docker history ${{ env.BASE_IMAGE_NAME }}-api:v${{ env.VERSION }} --format "table {{.CreatedBy}}\t{{.Size}}" | head -20
          echo ""
          echo "=== TOTAL IMAGE SIZE ==="
          docker image inspect ${{ env.BASE_IMAGE_NAME }}-api:v${{ env.VERSION }} --format='{{.Size}}' | numfmt --to=iec
          echo ""
          echo "=== DOCKER SYSTEM INFO ==="
          docker system df

      - name: Create GitHub pre-release
        run: |
          gh api \
            --method POST \
            --header "Accept: application/vnd.github+json" \
            /repos/${GITHUB_REPOSITORY}/releases \
            -f tag_name='v${{ env.VERSION }}' \
            -f target_commitish='main' \
            -f name='${{ env.VERSION }}' \
            -F prerelease=true \